import React, { useState } from 'react';
import {
  Bell,
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  Filter,
  CheckCheck,
  ShieldCheck,
  Search
} from 'lucide-react';
import { useWater } from '../context/WaterContext';
import { AlertCard } from '../components/alerts/AlertCard';
import { AlertSeverity } from '../types';

export const AlertsPage: React.FC = () => {
  const { alerts, markAlertResolved } = useWater();
  const [activeTab, setActiveTab] = useState<'All' | 'Critical' | 'Warning' | 'Resolved'>('All');
  const [search, setSearch] = useState('');

  const criticalCount = alerts.filter((a) => a.severity === 'critical' && a.status === 'active').length;
  const warningCount = alerts.filter((a) => a.severity === 'warning' && a.status === 'active').length;
  const resolvedCount = alerts.filter((a) => a.status === 'resolved').length;

  const filteredAlerts = alerts.filter((alert) => {
    let matchesTab = true;
    if (activeTab === 'Critical') matchesTab = alert.severity === 'critical' && alert.status === 'active';
    else if (activeTab === 'Warning') matchesTab = alert.severity === 'warning' && alert.status === 'active';
    else if (activeTab === 'Resolved') matchesTab = alert.status === 'resolved';

    const matchesSearch =
      alert.title.toLowerCase().includes(search.toLowerCase()) ||
      alert.location.toLowerCase().includes(search.toLowerCase()) ||
      alert.description.toLowerCase().includes(search.toLowerCase());

    return matchesTab && matchesSearch;
  });

  const resolveAllActive = () => {
    alerts
      .filter((a) => a.status === 'active')
      .forEach((a) => markAlertResolved(a.id));
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-900">
            Alert Management
          </h2>
          <p className="text-sm text-slate-500 mt-0.5">
            Active and historical anomaly notifications generated by the AquaGuard engine.
          </p>
        </div>

        {criticalCount + warningCount > 0 && (
          <button
            onClick={resolveAllActive}
            className="self-start sm:self-auto inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 shadow-2xs transition-colors"
          >
            <CheckCheck className="h-4 w-4 text-emerald-600" />
            <span>Acknowledge All Active</span>
          </button>
        )}
      </div>

      {/* Tabs & Search */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 border-b border-slate-200 pb-4">
        <div className="flex flex-wrap items-center gap-2">
          {(
            [
              { id: 'All', label: 'All Alerts', count: alerts.length },
              { id: 'Critical', label: 'Critical', count: criticalCount, color: 'text-rose-600' },
              { id: 'Warning', label: 'Warning', count: warningCount, color: 'text-amber-600' },
              { id: 'Resolved', label: 'Resolved', count: resolvedCount, color: 'text-emerald-600' },
            ] as const
          ).map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`rounded-lg px-3.5 py-1.5 text-xs font-semibold transition-all inline-flex items-center gap-1.5 ${
                activeTab === tab.id
                  ? 'bg-slate-900 text-white shadow-xs'
                  : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
              }`}
            >
              <span>{tab.label}</span>
              <span
                className={`rounded-full px-1.5 py-0.2 text-[10px] ${
                  activeTab === tab.id
                    ? 'bg-white/20 text-white'
                    : 'bg-slate-100 text-slate-700'
                }`}
              >
                {tab.count}
              </span>
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search alerts..."
            className="w-full rounded-lg border border-slate-200 bg-white py-1.5 pl-8 pr-3 text-xs text-slate-900 placeholder:text-slate-400 focus:border-cyan-500 focus:outline-none"
          />
        </div>
      </div>

      {/* Alert Cards List */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="rounded-xl border border-slate-200 bg-white p-12 text-center">
            <ShieldCheck className="mx-auto h-10 w-10 text-emerald-500 mb-2" />
            <h4 className="text-sm font-bold text-slate-900">No alerts in this category</h4>
            <p className="text-xs text-slate-500 mt-1">
              Water monitoring thresholds are balanced and within nominal expectations.
            </p>
          </div>
        ) : (
          filteredAlerts.map((alert) => (
            <AlertCard key={alert.id} alert={alert} />
          ))
        )}
      </div>
    </div>
  );
};
